version: "3.8"

services:
  # O Banco de Dados
  db:
    image: mariadb:latest
    container_name: spider_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - spider_net

  # O TÃºnel Tor (Existem imagens prontas e leves)
  tor:
    image: pickapp/tor-proxy:latest
    container_name: spider_tor
    restart: always
    ports:
      - "9050:9050"
    networks:
      - spider_net

  # O Nosso Minerador
  miner:
    build: .
    container_name: spider_app
    restart: always
    depends_on:
      - db
      - tor
    environment:
      - DB_HOST=db
      - TOR_HOST=tor
      - TOR_PORT=9050
    volumes:
      - ./.env:/app/.env
      - ./M/0/seeds.txt:/app/M/0/seeds.txt
    networks:
      - spider_net

networks:
  spider_net:
    driver: bridge
